### ISSUE TITLE
Trouble with collectstatic and setup.py

### ISSUE THREAD

**Issue by diegueus9** [dwaiter/django-ckeditor#3]
Hi,

I  just do this:

git clone https://github.com/dwaiter/django-ckeditor.git
python setup.py install

added to my INSTALLED_APPS

and python manage.py collectstatic

0 static files copied to '/.../static' (665 unmodified).

I think the problem is setup.py install doesn't copy static folder.

**Comment by overshard** [comment]
I have fixed this in issue #7 pull request along with templates problem too.
